name: "Rebuild Site"
on:
  workflow_dispatch:
  push:

jobs:
  setup:
    name: "Setup"
    runs-on: "ubuntu-latest"
    outputs:
      repo: ${{ steps.echo.outputs.repo }}
      email: ${{ steps.echo.outputs.email }}
      slub: ${{ steps.echo.outputs.slug }}
    steps:
      - id: echo
        run: |
          name="${{ github.event.repository.name }}"
          owner="${{ env.GITHUB_ACTOR || env.GITHUB_REPOSITORY_OWNER }}"
          id="${{ env.GITHUB_ACTOR_ID || env.GITHUB_REPOSITORY_OWNER_ID}}"
          email="$id+$owner@users.noreply.github.com"
          echo [{'"'name'"': '"'$name'"', '"'owner'"': '"'$owner'"'}] >> "$GITHUB_OUTUPT"
          echo slug=$owner >> "$GITHUB_OUTPUT"
          echo email=$email >> "$GITHUB_OUTPUT"
  site:
    needs: [setup]
    uses: hubverse-org/hub-dashboard-control-room/.github/workflows/generate-site.yaml@znk/no-token
    with:
      repos: '${{ fromJSON(needs.setup.outputs.repo) }}'
      slug: '${{ needs.setup.outputs.slug }}'
      email: '${{ needs.setup.outputs.email }}'
    secrets:
      token: ${{ github.token }}
