name: "Rebuild Site"
on:
  workflow_dispatch:
  push:

jobs:
  setup:
    name: "Setup"
    runs-on: "ubuntu-latest"
    outputs:
      repo: ${{ steps.echo.outputs.repo }}
      email: ${{ steps.echo.outputs.email }}
    steps:
      run: |
        name="${{ github.event.repository.name }}"
        owner="${{ env.GITHUB_ACTOR }}"
        email="${{ env.GITHUB_ACTOR_ID }}+$owner@users.noreply.github.com"
        {
          echo repo<<EOF
          echo [{"name": "$name", "owner": "$owner"}]
          echo EOF
        } >> "$GITHUB_OUTUPT"
        echo slug=$owner >> "$GITHUB_OUTPUT"
        echo email=$email >> "$GITHUB_OUTPUT"
  site:
    needs: [setup]
    uses: hubverse-org/hub-dashboard-control-room/.github/workflows/generate-site.yaml@znk/no-token
    with:
      repos: '${{ fromJSON(needs.setup.outputs.repo) }}'
      slug: '${{ env.GITHUB_ACTOR }}'
      email: '${{ needs.setup.outputs.email }}'
    secrets:
      token: ${{ github.token }}
